### ISSUE TITLE
Support for GQL body variables.

### ISSUE THREAD

**Issue by ChangoBuitrago** [energywebfoundation/passport-did-auth#14]
The module works great for REST-based integrations, but for Graphql-based solutions, changes may need to be done. So far, my only suggestion is the following:

At to the `extractToken` method (`line-172`) of the `LoginStrategy.ts` file, add an extra validation to `req.body`: 
`|| lookup(req.body.variables, this.claimField)`. `body.variables` is the standard way to pass body params using `gql` APIs. 

```
  extractToken(req: Request) {
    return (
      lookup(req.body, this.claimField) || lookup(req.query, this.claimField) || lookup(req.body.variables, this.claimField)
    )
  }
```

**Comment by Harasz** [comment]
Hi @ChangoBuitrago, I've added task to our board. We will back to the issue as soon as it is possible.
