### ISSUE TITLE
Process crashes when malformed identity token provided.

### ISSUE THREAD

**Issue by artursudnik** [energywebfoundation/passport-did-auth#294]
After calling an endpoint covered with LoginStrategy with malformed identity token like for instance
```json
{
    "identityToken": "sdfsdfsdf"
}
```
the whole nodejs process crashes after an exception is thrown in the following line: https://github.com/energywebfoundation/passport-did-auth/blob/1df78a155f12c09429d5652de3f61668850142c2/lib/LoginStrategy.ts#L146-L146

```
/mydid-protected-service/node_modules/passport-did-auth/dist/lib/LoginStrategy.js:110
            const iss = this.didUnification(payload.iss);
                                                    ^
TypeError: Cannot read properties of null (reading 'iss')
```

This makes it very easy to perform DOS attacks.

**Comment by jrhender** [comment]
Thanks for reporting @artursudnik . Logged https://energyweb.atlassian.net/browse/PDA-46, hopefully we will fix next sprint

**Comment by Harasz** [comment]
Fixed in https://github.com/energywebfoundation/passport-did-auth/pull/297
