### ISSUE TITLE
Please allow compile in ts strict #104

### ISSUE THREAD

**Issue by Rjrunner44** [energywebfoundation/passport-did-auth#30]
thx (related to usage within iam-client-lib also issue #104 there): 

https://github.com/energywebfoundation/iam-client-lib/issues/104

**Comment by Rjrunner44** [comment]
hey, could we bump this in priority now? It would be very helpful. The more devs that start to code against the lib the more important this will become also. Thanks 🙏

**Comment by jrhender** [comment]
Typescript app (NestJs) using passport-did-auth can compile with `strict` and `skipLibCheck=false`. https://github.com/energywebfoundation/iam-client-examples/tree/feat/compile-nest-in-strict

After discussion with @Rjrunner44, typescript compile errors seem to be stemming from ew-did-registry. After opening an issue there, will reference here and close this issue.

**Comment by jrhender** [comment]
Compilation errors only occur when `skipLibCheck: false`. Errors are in ew-did-registry packages. Issue opened in that repository to fix: energywebfoundation/ew-did-registry#270
