### ISSUE TITLE
Missing documentation on the login payload

### ISSUE THREAD

**Issue by kosecki123** [energywebfoundation/passport-did-auth#46]
When using `passport-did-auth` with your own web application it's pretty much unknown what is expected to be sent to your `login` endpoint which uses strategies from `passport-did-auth`. This is especially important as use of `iam-client-lib` is not mandatory and users can construct login data `identityToken` manually.

**Comment by Harasz** [comment]
Hi @kosecki123, we will fill gaps in our documentation as soon as it is possible. Thanks for reporting.

**Comment by Harasz** [comment]
Added in https://github.com/energywebfoundation/passport-did-auth/pull/298
