### ISSUE TITLE
avoid hard coded values

### ISSUE THREAD

**Issue by drgorb** [energywebfoundation/passport-did-auth#5]
It would be beneficial if we avoided hard coded addresses and networks. 

* remove the reference to Volta as this will need to work on the EWC as well
* put all smart contract addresses in `.env`
* put URLs in `.env` (e.g. ipfsUrl)

https://github.com/energywebfoundation/passport-did-auth/blob/1fe9ce64bfc5311527757eb3e057885b1854e7e2/lib/LoginStrategy.ts#L54

**Comment by Harasz** [comment]
I close the issue, because we will fix it together with #6
